import React from 'react'
import styles from './css/page.module.css'

function Page7() {
  return (
    <div className={styles.container}>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat, at. Harum, sed, consectetur delectus maxime magni quod repellendus cupiditate accusamus illo debitis blanditiis, quidem dicta deserunt eum consequatur! Iusto, in.
      Magni laborum perferendis, reiciendis nam optio iste quod, consectetur fuga voluptatum nostrum totam at quam numquam sequi ab veniam recusandae dolorem ipsum blanditiis vero eaque beatae earum. Vel, quas cumque.
      Qui consectetur quisquam nostrum architecto inventore, necessitatibus amet illo quasi voluptatum cupiditate quaerat vero expedita, sint saepe aspernatur quis facilis eligendi sunt, harum nihil voluptatibus ipsum! Ipsam ad assumenda deleniti?
      Neque dicta quae veritatis quia vitae consequatur perferendis odit autem amet! Accusantium animi quibusdam dolores, in aperiam voluptates dolore officiis veniam. Rerum, vero esse repellendus eligendi voluptates cumque possimus velit!
      Blanditiis sequi minus exercitationem? Ex repellendus reiciendis quibusdam laudantium, quisquam libero iure saepe. Aut nulla beatae commodi facere possimus expedita explicabo, laborum error quia repellat odio assumenda neque quaerat ratione.
      Adipisci natus eos fuga minima sint nisi soluta minus neque consequatur inventore possimus labore molestiae voluptates voluptatibus recusandae, exercitationem facilis deserunt officiis veniam laborum doloremque omnis quis temporibus eveniet! Cupiditate!
      Aperiam incidunt in laudantium sint culpa, adipisci et ut. Asperiores repellat ab ipsam dicta, quibusdam eum nemo, ea, pariatur cupiditate ex earum.
      Nobis possimus sint dolorum, earum dicta fugiat tenetur placeat quas rem ad, unde aut ab dolorem adipisci incidunt veniam aliquam quia repellendus distinctio, molestias consectetur ea numquam esse? Reiciendis, ipsam!
      Similique porro dolor veniam accusamus quam, vero ad recusandae velit rerum fugit maxime animi nemo doloremque soluta? Cum voluptas ad placeat tempora hic molestiae sunt. Repellendus, corporis deleniti! Facere, quasi?
      Eius, consequuntur blanditiis incidunt deserunt, aperiam repellendus dolor id quas distinctio amet quaerat ea placeat labore repellat quis sapiente voluptatem est quo, harum fugit numquam eos ex quia laudantium! Earum?
      Amet, quaerat possimus beatae eos fugiat molestias sunt deleniti doloremque dignissimos? Incidunt, voluptas sit impedit neque, nobis expedita vel facere voluptatum perferendis sapiente magni amet architecto porro, dolorum voluptate accusamus!
      Fugit nulla aperiam officia ex illum, rerum temporibus ea labore velit et, cum magni ipsam id nemo, inventore possimus sunt non. Fugiat iure reiciendis illum nihil recusandae adipisci maxime omnis.
      Error at mollitia nobis possimus, atque officiis asperiores repellat. Assumenda impedit veniam magnam modi! Incidunt voluptatum hic ad impedit eaque repellendus atque deserunt, libero vitae, aspernatur neque possimus delectus sapiente!
      Eaque laborum dignissimos nihil error? Nisi unde neque error ipsam culpa delectus eligendi totam. Praesentium incidunt natus laudantium atque provident ad rerum. Quibusdam, dolorem. Esse molestias amet assumenda! Laudantium, soluta.
      Possimus facilis quo officia vel cumque, esse pariatur consequatur similique quaerat vero sequi animi laborum fuga obcaecati? Placeat culpa quibusdam exercitationem quis, vero laudantium nam repudiandae, optio voluptas, aut assumenda?
      Quo sit explicabo consectetur velit officia labore debitis, asperiores provident animi rerum. Hic, illo assumenda asperiores nisi optio magni qui saepe corporis enim repellat cum, quasi repellendus? Cumque, hic modi.
      Architecto, saepe! Perferendis cum fugit iusto ea soluta veniam ab atque modi ducimus esse quaerat voluptatibus dicta suscipit dolore voluptatem nesciunt ex aliquid earum nobis, quae doloribus. Eius, hic dignissimos.
      Dignissimos sapiente delectus ullam impedit voluptatum quam quasi reiciendis blanditiis. Possimus, vel unde? Dignissimos impedit nam odio natus! Maiores, possimus suscipit. Magni ipsa laborum perspiciatis fuga, ut laboriosam in unde?
      Voluptatum suscipit aut sint nulla eligendi quis id eveniet fugiat error laborum commodi laudantium, maiores ipsa quasi quo tenetur iure animi? Maxime consectetur, cupiditate distinctio necessitatibus magnam nulla beatae in.
      Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias ignissimos sapiente delectus ullam impedit voluptatum quam quasi reiciendis blanditiis. Possimus, vel unde? Dignissimos impedit nam odio natus! Maiores, possimus suscipit. Magni ipsa laborum perspiciatis fuga, ut laboriosam in unde?
      Voluptatum suscipit aut sint nulla eligendi quis id eveniet fugiat error laborum commodi laudantium, maiores ipsa quasi quo tenetur iure animi? Maxime consectetur, cupiditate distinctio necessitatibus magnam nulla beatae in.
      Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias ignissimos sapiente delectus ullam impedit voluptatum quam quasi reiciendis blanditiis. Possimus, vel unde? Dignissimos impedit nam odio natus! Maiores, possimus suscipit. Magni ipsa laborum perspiciatis fuga, ut laboriosam in unde?
      Voluptatum suscipit aut sint nulla eligendi quis id eveniet fugiat error laborum commodi laudantium, maiores ipsa quasi quo tenetur iure animi? Maxime consectetur, cupiditate distinctio necessitatibus magnam nulla beatae in.
      Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias ignissimos sapiente delectus ullam impedit voluptatum quam quasi reiciendis blanditiis. Possimus, vel unde? Dignissimos impedit nam odio natus! Maiores, possimus suscipit. Magni ipsa laborum perspiciatis fuga, ut laboriosam in unde?
      Voluptatum suscipit aut sint nulla eligendi quis id eveniet fugiat error laborum commodi laudantium, maiores ipsa quasi quo tenetur iure animi? Maxime consectetur, cupiditate distinctio necessitatibus magnam nulla beatae in.
      Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eiusneque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eius. Harum eum fugiat aliquam eius omnis, suscipit, laboriosam recusandae qui dolore inventore ex nam soluta dolorem.Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eius. Harum eum fugiat aliquam eius omnis, suscipit, laboriosam recusandae qui dolore inventore ex nam soluta dolorem.Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eius. Harum eum fugiat aliquam eius omnis, suscipit, laboriosam recusandae qui dolore inventore ex nam soluta dolorem.Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eius. Harum eum fugiat aliquam eius omnis, suscipit, laboriosam recusandae qui dolore inventore ex nam soluta dolorem.Libero, neque asperiores? Eveniet recusandae aperiam laboriosam optio quo incidunt suscipit porro molestias eius. Harum eum fugiat aliquam eius omnis, suscipit, laboriosam recusandae qui dolore inventore ex nam soluta dolorem.
  
    </div>
  )
}

export default Page7